### ISSUE TITLE
Can't deploy contract

### ISSUE THREAD

**Issue by diepvuongthang** [hashgraph/hethers.js#239]
Note: Not all sections may be relevant, but please be as thorough while remaining concise as possible. Remove this Notice and any sections that don't feel pertinent.

If you are unsure if something is a bug, start a thread in the *"discussions"* tab above..

**Describe the bug**

**Reproduction steps**
Please include code snippets, with console.log output, any contract ABI, contract address, network and the full error.

**Environment:**
Please include anything that may be useful in diagnosing the issue. Node vs Browser? Geth vs Parity vs Ganache? Third Party tools, like Hardhat? Mobile vs. Desktop?

**Search Terms**
<img width="1432" alt="Screen Shot 2022-05-11 at 00 15 17" src="https://user-images.githubusercontent.com/15863694/167685301-dac1a825-d220-49d3-a250-9d4ffb1dad4c.png">

Often similar issues have come up before. Include any search terms you have tried in this repository's Issues (including closed issues) and *"Discussions"*, so if there are matching issues, we can be sure to add those keywords and link this issue to it, making it easier for people to find in the future.

**Comment by Kalina-Todorova** [comment]
Could you share a bit more context - what are you trying to achieve and if possible the code of the smart contract in a txt format so that we can debug?

**Comment by yogeshrt** [comment]
\hedera\node_modules\@hethers\logger\lib\index.js:186
        var error = new Error(message);
                    ^

Error: transaction 0.0.48162428@1663101679.615115293 failed precheck with status INVALID_SIGNATURE (code=INVALID_SIGNATURE, version=providers/1.2.1)
    at Logger.makeError (C:\Users\Yogesh\hedera\node_modules\@hethers\logger\lib\index.js:186:21)
    at DefaultHederaProvider.<anonymous> (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:690:38)
    at step (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:78:23)
    at Object.throw (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:59:53)
    at rejected (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'transaction 0.0.48162428@1663101679.615115293 failed precheck with status INVALID_SIGNATURE',
  code: 'INVALID_SIGNATURE',
  transaction: {
    transactionId: '0.0.48162428-1663101679-615115293',
    hash: '0xf9b33156f07d33265aa22fa3cd031e48e7cecda781e00db096f592f44c9a2bb88543dbfe8f49c7da023a9d8340593bde',
    from: '0x0000000000000000000000000000000002dee67c',
    data: '0x30783630383036303430353233343830313536313030313035373630303038306664356235303630343035313631303362633338303338303631303362633833333938313031363034303831393035323631303032663931363130303763353635623630343035313831383135323333393036303030393037666464663235326164316265326338396236396332623036386663333738646161393532626137663136336334613131363238663535613464663532336233656639303630323030313630343035313830393130333930613333333630303039303831353236303230383139303532363034303930323035353631303039343536356236303030363032303832383430333132313536313030386435373830383166643562353035313931393035303536356236313033313938303631303061333630303033393630303066336665363038303630343035323334383031353631303031303537363030303830666435623530363030343336313036313030346335373630303033353630653031633830363333313363653536373134363130303531353738303633373061303832333131343631303036353537383036333935643839623431313436313030396335373830363361393035396362623134363130306335353735623630303038306664356236303430353136303132383135323630323030313562363034303531383039313033393066333562363130303865363130303733333636303034363130323031353635623630303136303031363061303162303331363630303039303831353236303230383139303532363034303930323035343930353635623630343035313930383135323630323030313631303035633536356236303430383035313830383230313832353236303037383135323636323662636161333762356232623736306339316236303230383230313532393035313631303035633931393036313032346235363562363130306438363130306433333636303034363130323232353635623631303065383536356236303430353139303135313538313532363032303031363130303563353635623333363030303930383135323630323038313930353236303430383132303534383231313135363130313462353736303430353136323436316263643630653531623831353236303230363030343832303135323630316136303234383230313532376636393665373337353636363636393633363936353665373432303734366636623635366532303632363136633631366536333635303030303030303030303030363034343832303135323630363430313630343035313830393130333930666435623333363030303930383135323630323038313930353236303430383132303830353438343932393036313031366139303834393036313032623635363562393039313535353035303630303136303031363061303162303338333136363030303930383135323630323038313930353236303430383132303830353438343932393036313031393739303834393036313032396535363562393039313535353035303630343035313832383135323630303136303031363061303162303338343136393033333930376664646632353261643162653263383962363963326230363866633337386461613935326261376631363363346131313632386635356134646635323362336566393036303230303136303430353138303931303339306133353036303031393239313530353035363562383033353630303136303031363061303162303338313136383131343631303166633537363030303830666435623931393035303536356236303030363032303832383430333132313536313032313235373830383166643562363130323162383236313031653535363562393339323530353035303536356236303030383036303430383338353033313231353631303233343537383038316664356236313032336438333631303165353536356239343630323039333930393330313335393335303530353035363562363030303630323038303833353238333531383038323835303135323832356238313831313031353631303237373537383538313031383330313531383538323031363034303031353238323031363130323562353635623831383131313135363130323838353738333630343038333837303130313532356235303630316630313630316631393136393239303932303136303430303139333932353035303530353635623630303038323139383231313135363130326231353736313032623136313032636435363562353030313930353635623630303038323832313031353631303263383537363130326338363130326364353635623530303339303536356236333465343837623731363065303162363030303532363031313630303435323630323436303030666466656132363436393730363637333538323231323230643830333834636535383465313031633562393265346565396237383731323632323835303730646263643264373166393936303166306634666365636432333634373336663663363334333030303830343030333330303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303634',
    chainId: 0,
    r: '',
    s: '',
    v: 0
  },
  transactionHash: '0xf9b33156f07d33265aa22fa3cd031e48e7cecda781e00db096f592f44c9a2bb88543dbfe8f49c7da023a9d8340593bde'
}

**Comment by yogeshrt** [comment]
We are trying to submit a small smart contract on hedera DLT using hethers. If needed I can share sample index.js for review/comments.

**Comment by Kalina-Todorova** [comment]
We suspect that it might be related to the way the wallet was initialized. You could take a look at the docs: https://docs.hedera.com/hethers/application-programming-interface/signers#new-hethers.wallet-less-than-externallyownedaccount-greater-than-provider
If this doesn't help you, please send us the whole code snippet so that we can verify.

**Comment by yogeshrt** [comment]
const { hethers } = require('@hashgraph/hethers');
require("dotenv").config();
const { PrivateKey } = require("@hashgraph/sdk");

async function main() {
	
    //Grab your Hedera testnet account ID and private key from your .env file
	const myAccountId = process.env.MY_ACCOUNT_ID;
	const myPrivateKey = process.env.MY_PRIVATE_KEY;

	// If we weren't able to grab it, we should throw a new error
	if (myAccountId == null ||
		myPrivateKey == null ) {
		throw new Error("Environment variables myAccountId and myPrivateKey must be present");
	}
	
	// available default providers ['mainnet', 'testnet', 'previewnet']
	const provider = hethers.providers.getDefaultProvider('testnet');
	const balance = await provider.getBalance('0.0.48162428');
	console.log("The balance is: " +balance);
    const eoaAccount = {
        account: "0.0.48162428",
        privateKey: "0x302e020100300506032b65700422042091882ca433ba668a484dedbbb6319cd11a580ebe1b491d23fdd7a534f6cf2669" 
    };

    const wallet2 = new hethers.Wallet(eoaAccount, provider);
    console.log("Wallet address =", wallet2.getAddress());

	const mywallet = new hethers.Wallet(myPrivateKey, provider);
	//const connectedViaAccountId  = mywallet.connectAccount('0.0.48162428'); // ??

const bytecode = "0x608060405234801561001057600080fd5b506040516103bc3803806103bc83398101604081905261002f9161007c565b60405181815233906000907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a333600090815260208190526040902055610094565b60006020828403121561008d578081fd5b5051919050565b610319806100a36000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063313ce5671461005157806370a082311461006557806395d89b411461009c578063a9059cbb146100c5575b600080fd5b604051601281526020015b60405180910390f35b61008e610073366004610201565b6001600160a01b031660009081526020819052604090205490565b60405190815260200161005c565b604080518082018252600781526626bcaa37b5b2b760c91b6020820152905161005c919061024b565b6100d86100d3366004610222565b6100e8565b604051901515815260200161005c565b3360009081526020819052604081205482111561014b5760405162461bcd60e51b815260206004820152601a60248201527f696e73756666696369656e7420746f6b656e2062616c616e6365000000000000604482015260640160405180910390fd5b336000908152602081905260408120805484929061016a9084906102b6565b90915550506001600160a01b0383166000908152602081905260408120805484929061019790849061029e565b90915550506040518281526001600160a01b0384169033907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef9060200160405180910390a350600192915050565b80356001600160a01b03811681146101fc57600080fd5b919050565b600060208284031215610212578081fd5b61021b826101e5565b9392505050565b60008060408385031215610234578081fd5b61023d836101e5565b946020939093013593505050565b6000602080835283518082850152825b818110156102775785810183015185820160400152820161025b565b818111156102885783604083870101525b50601f01601f1916929092016040019392505050565b600082198211156102b1576102b16102cd565b500190565b6000828210156102c8576102c86102cd565b500390565b634e487b7160e01b600052601160045260246000fdfea2646970667358221220d80384ce584e101c5b92e4ee9b7871262285070dbcd2d71f99601f0f4fcecd2364736f6c63430008040033";

// A Human-Readable ABI; we only need to specify relevant fragments,
// in the case of deployment this means the constructor
const abi = [
    "constructor(uint totalSupply)"
];

console.log("before contractfactory");
const factory = new hethers.ContractFactory(abi, bytecode, wallet2);


console.log("before factory.deploy");
// Deploy, setting total supply to 100 tokens (assigned to the deployer)
const contract = await factory.deploy(100, {gasLimit: 3000000});

// The contract is not currentl live on the network yet, however
// its address is ready for us
console.log("contract address = ",contract.address);
// '0x0000000000000000000000000000000001c50c95'

// Wait until the contract has been deployed before interacting
// with it; returns the receipt for the deployemnt transaction
const resp1 = await contract.deployTransaction.wait();
console.log("responce  = ",resp1);
}

main();

**Comment by yogeshrt** [comment]
node .\hethers_test.js
The balance is: 999256518542
Wallet address = Promise { '0x0000000000000000000000000000000002dee67c' }
before contractfactory
before factory.deploy
C:\Users\Yogesh\hedera\node_modules\@hethers\logger\lib\index.js:186
        var error = new Error(message);
                    ^

Error: transaction 0.0.48162428@1663162799.267505558 failed precheck with status INVALID_SIGNATURE (code=INVALID_SIGNATURE, version=providers/1.2.1)
    at Logger.makeError (C:\Users\Yogesh\hedera\node_modules\@hethers\logger\lib\index.js:186:21)
    at DefaultHederaProvider.<anonymous> (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:690:38)
    at step (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:78:23)
    at Object.throw (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:59:53)
    at rejected (C:\Users\Yogesh\hedera\node_modules\@hethers\providers\lib\base-provider.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'transaction 0.0.48162428@1663162799.267505558 failed precheck with status INVALID_SIGNATURE',
  code: 'INVALID_SIGNATURE',
  transaction: {
    transactionId: '0.0.48162428-1663162799-267505558',
    hash: '0x2b982d71144f109751251140a9cc064126c4f1265258c4e32d30dd259b56239ae1ad8eeade6c1fb418442ade612b4fae',
    from: '0x0000000000000000000000000000000002dee67c',
    data: '0x30783630383036303430353233343830313536313030313035373630303038306664356235303630343035313631303362633338303338303631303362633833333938313031363034303831393035323631303032663931363130303763353635623630343035313831383135323333393036303030393037666464663235326164316265326338396236396332623036386663333738646161393532626137663136336334613131363238663535613464663532336233656639303630323030313630343035313830393130333930613333333630303039303831353236303230383139303532363034303930323035353631303039343536356236303030363032303832383430333132313536313030386435373830383166643562353035313931393035303536356236313033313938303631303061333630303033393630303066336665363038303630343035323334383031353631303031303537363030303830666435623530363030343336313036313030346335373630303033353630653031633830363333313363653536373134363130303531353738303633373061303832333131343631303036353537383036333935643839623431313436313030396335373830363361393035396362623134363130306335353735623630303038306664356236303430353136303132383135323630323030313562363034303531383039313033393066333562363130303865363130303733333636303034363130323031353635623630303136303031363061303162303331363630303039303831353236303230383139303532363034303930323035343930353635623630343035313930383135323630323030313631303035633536356236303430383035313830383230313832353236303037383135323636323662636161333762356232623736306339316236303230383230313532393035313631303035633931393036313032346235363562363130306438363130306433333636303034363130323232353635623631303065383536356236303430353139303135313538313532363032303031363130303563353635623333363030303930383135323630323038313930353236303430383132303534383231313135363130313462353736303430353136323436316263643630653531623831353236303230363030343832303135323630316136303234383230313532376636393665373337353636363636393633363936353665373432303734366636623635366532303632363136633631366536333635303030303030303030303030363034343832303135323630363430313630343035313830393130333930666435623333363030303930383135323630323038313930353236303430383132303830353438343932393036313031366139303834393036313032623635363562393039313535353035303630303136303031363061303162303338333136363030303930383135323630323038313930353236303430383132303830353438343932393036313031393739303834393036313032396535363562393039313535353035303630343035313832383135323630303136303031363061303162303338343136393033333930376664646632353261643162653263383962363963326230363866633337386461613935326261376631363363346131313632386635356134646635323362336566393036303230303136303430353138303931303339306133353036303031393239313530353035363562383033353630303136303031363061303162303338313136383131343631303166633537363030303830666435623931393035303536356236303030363032303832383430333132313536313032313235373830383166643562363130323162383236313031653535363562393339323530353035303536356236303030383036303430383338353033313231353631303233343537383038316664356236313032336438333631303165353536356239343630323039333930393330313335393335303530353035363562363030303630323038303833353238333531383038323835303135323832356238313831313031353631303237373537383538313031383330313531383538323031363034303031353238323031363130323562353635623831383131313135363130323838353738333630343038333837303130313532356235303630316630313630316631393136393239303932303136303430303139333932353035303530353635623630303038323139383231313135363130326231353736313032623136313032636435363562353030313930353635623630303038323832313031353631303263383537363130326338363130326364353635623530303339303536356236333465343837623731363065303162363030303532363031313630303435323630323436303030666466656132363436393730363637333538323231323230643830333834636535383465313031633562393265346565396237383731323632323835303730646263643264373166393936303166306634666365636432333634373336663663363334333030303830343030333330303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303634',
    chainId: 0,
    r: '',
    s: '',
    v: 0
  },
  transactionHash: '0x2b982d71144f109751251140a9cc064126c4f1265258c4e32d30dd259b56239ae1ad8eeade6c1fb418442ade612b4fae'
}

**Comment by yogeshrt** [comment]
[heathers_test.txt](https://github.com/hashgraph/hethers.js/files/9566843/heathers_test.txt)

**Comment by yogeshrt** [comment]
const eoaAccount = {
        account: "0.0.48162428",
        privateKey: "0x302e020100300506032b65700422042091882ca433ba668a484dedbbb6319cd11a580ebe1b491d23fdd7a534f6cf2669" 
    };

    const wallet2 = new hethers.Wallet(eoaAccount, provider);
    const factory = new hethers.ContractFactory(abi, bytecode, wallet2);

**Comment by yogeshrt** [comment]
Provisioned wallet with eoaAccount way with account and privatekey ( Note this is on testnet hence sharing keys/account Id). Thanks in advance for your support.

**Comment by Kalina-Todorova** [comment]
Hi @yogeshrt I think the privateKey is the issue as it should be without the 0x prefix. Could you try and let us know if this works?

**Comment by yogeshrt** [comment]
@Kalina-Todorova I was about to resolve issues with the below notes
1) Account generation from https://portal.hedera.com/register create Privatekey with ED25519
2) Account generated through the program using PrivateKey.generateECDSA() can be a way to create with private key ECDSA pfa reference program for the same
[accountgenerate_ecdsa.txt](https://github.com/hashgraph/hethers.js/files/9585922/accountgenerate_ecdsa.txt)
3) Account genarated with step (2) has 0 hbar, so cant be used for deploy contracts
4) Used program to transfer balance from account[ generated from step 1] to account [ generated from step 2] 
[account_transfer_hbar.txt](https://github.com/hashgraph/hethers.js/files/9585931/account_transfer_hbar.txt)
5) account [ generated from step 2] is ready to be used for deploying the contract
[deploy_contract.txt](https://github.com/hashgraph/hethers.js/files/9585940/deploy_contract.txt)

Note: This program requires cleanup. But the scenario is successfully tested with it.

**Comment by yogeshrt** [comment]
https://github.com/hashgraph/hethers.js/pull/234 This commit mentioned adding support for ED25519, but not sure why we still require the ECDSA key with hethers.

**Comment by bmino** [comment]
I experienced the same issue. Initializing a wallet using a non-ECDSA private key was the issue. Some options now include:
```javascript
const wallet = new hethers.Wallet({
    account: accountId,
    privateKey: privateKey,
    isED25519Type: true,
});
```

**Comment by Kalina-Todorova** [comment]
Let us will look into it and get back to you
