### ISSUE TITLE
Running hethers v1.1.4 with js sdk 2.17.1 (same project) results in errors

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hethers.js#270]
**Describe the bug**
A project containing both hethers and the hedera js sdk (versions 1.1.4 and 2.17.1) result in the following error:

```
TypeError: Cannot read properties of undefined (reading 'encode')
    at Wallet.<anonymous> (node_modules/@hethers/abstract-signer/lib/index.js:237:64)
    at step (node_modules/@hethers/abstract-signer/lib/index.js:78:23)
    at Object.next (node_modules/@hethers/abstract-signer/lib/index.js:59:53)
    at fulfilled (node_modules/@hethers/abstract-signer/lib/index.js:50:58)
 ```

note that deploying contracts appears to work, calling or querying them doesn't.

**Reproduction steps**
Setup a project with the above dependencies and execute or call a contract function.

**Environment:**
node version v16.13.0

**Comment by gregscullard** [comment]
this combination works
    "@hashgraph/hethers": "1.1.3",
    "@hashgraph/sdk": "2.11.0",

upgrading to 1.1.4 results in the error above
